{% set name = "nginx" %}
{% set version = "1.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://nginx.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: 002d9f6154e331886a2dd4e6065863c9c1cf8291ae97a1255308572c02be9797
  patches:
    - pcre-config.patch  # find pcre in PREFIX instead of /usr

build:
  number: 0
  no_link:
    - etc/*
    - var/log/nginx/*
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libgd 2.2.*
    - libxslt 1.1.*
    - openssl
    - pcre 8.*
    - zlib
  run:
    - libgd 2.2.*
    - libxslt 1.1.*
    - openssl
    - pcre 8.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [unix]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.nginx.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
  description: |
    Nginx can act as a reverse proxy server for TCP, UDP, HTTP, HTTPS, SMTP,
    POP3, IMAP, and gRPC protocols, as well as a load balancer and an HTTP cache.
    Nginx uses an asynchronous event-driven approach to handling requests.
  doc_url: http://nginx.org/en/docs
  dev_url: http://hg.nginx.org/nginx

extra:
  recipe-maintainers:
    - sodre
