{% set name = "nginx" %}
{% set version = "1.17.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://nginx.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: 63ee35e15a75af028ffa1f995e2b9c120b59ef5f1b61a23b8a4c33c262fc10c3
  patches:
    - pcre-config.patch  # find pcre in PREFIX instead of /usr

build:
  number: 0
  no_link:
    - etc/*
    - var/log/nginx/*
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - libgd 2.2.*
    - libxslt 1.1.*
    - openssl
    - pcre 8.*
    - zlib
  run:
    - libgd 2.2.*
    - libxslt 1.1.*
    - openssl
    - pcre 8.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [unix]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.nginx.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
  description: |
    Nginx can act as a reverse proxy server for TCP, UDP, HTTP, HTTPS, SMTP,
    POP3, IMAP, and gRPC protocols, as well as a load balancer and an HTTP cache.
    Nginx uses an asynchronous event-driven approach to handling requests.
  doc_url: http://nginx.org/en/docs
  dev_url: http://hg.nginx.org/nginx

extra:
  recipe-maintainers:
    - sodre
