{% set name = "nginx" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://nginx.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: 77a2541637b92a621e3ee76776c8b7b40cf6d707e69ba53a940283e30ff2f55d

  patches:
    - pcre-config.patch  # find pcre in PREFIX instead of /usr

build:
  number: 0
  no_link:
    - etc/*
    - var/log/nginx/*
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - libgd
    - libxslt
    - openssl
    - pcre2
    - zlib

test:
  commands:
    - nginx -h
  requires:
    - curl

about:
  home: http://www.nginx.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
  description: |
    Nginx can act as a reverse proxy server for TCP, UDP, HTTP, HTTPS, SMTP,
    POP3, IMAP, and gRPC protocols, as well as a load balancer and an HTTP cache.
    Nginx uses an asynchronous event-driven approach to handling requests.
  doc_url: http://nginx.org/en/docs
  dev_url: http://hg.nginx.org/nginx

extra:
  recipe-maintainers:
    - sodre
    - fhoehle
