appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Fq7dk00+X1PsyZlPNRdkbyqMCbpPZrd2qEhrKqhtxQgtv3OLsAkgFdirC7/cL2SwGerJ5yiWtyTOEfGto30keZ7WP2Tp6QvgslUNGJNhl5/EKJu4lDU/SnyIc26wUE/P8zLSDtWxmhKE7dF7/mbkaKcGVe8btmyW5cdwu9AtOUnV3/38JMe42RbfcyIGIkvTBN5OjR3LhSZ+hj5WNW2nDiG7jlzqAq3B9ucgCWXa+HdEOo9WfDW/BgJZg/LG3HIR14IOLVx1dviiki878nvkW8EZCp3zerI6vWFCj7fQ2F9Bz4syZsMYYtw8Oy2+QK2YInJEfqIk3X0rT2q2BhwDnweEAZ328uEjsq/vN+UNOIDp7JLCBtULEeMbRDBVfQSI8cN2uBlgqy+sxKOEbLgyB63HnI+rqdjYJ8Fr6lc0kGqHG6/b8xvUlM/IE18/mPW7clSaiZ59cC7ZVyfsQcERZCD/rTUJoGrCDXfcfrat+3Tb3Fsp4xbx+GTpB3kn8BG+N5kHbskV9ilwCYwWfoK/ifnhY8VwZKn7BskXTc4zgqEzPEn0oGL0e5gpstUW/519V1tHHUo5hgtLg/mSxVwP7orcI3R4UuZIm52ER0E8chnIRvr5wFbjLRltnyvlFSWfg2eD81ACZYLOtYR2r0b72t7x3+S5ibkkigZPWxIgRsc=}
conda_forge_output_validation: true
